name: Deploy
on:
  pull_request:
    types: 
      - synchronize
    branches:
      - main
      
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          echo ${{ secrets.USERNAME }}
          cd repo
          cd be
          cd backend-airbnb
          git pull origin main
          docker-compose down --rmi all && docker-compose up --build -d
